// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSVW7O8iyNRe33wAKmlzKGCfAjM8OuhKs',
    appId: '1:77712420958:web:9ae1c77148906c3b4b84cf',
    messagingSenderId: '77712420958',
    projectId: 'moztiq-nc-tiktok-clone',
    authDomain: 'moztiq-nc-tiktok-clone.firebaseapp.com',
    storageBucket: 'moztiq-nc-tiktok-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD6aoriDRox7IMiSMBIbdlUMX_qMs81xA',
    appId: '1:77712420958:android:20130c7db0b60ad04b84cf',
    messagingSenderId: '77712420958',
    projectId: 'moztiq-nc-tiktok-clone',
    storageBucket: 'moztiq-nc-tiktok-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAECmv5DK5Z22nGYhmkE4mtB9Pt6FHyNs',
    appId: '1:77712420958:ios:ab61afdbcfb30fe14b84cf',
    messagingSenderId: '77712420958',
    projectId: 'moztiq-nc-tiktok-clone',
    storageBucket: 'moztiq-nc-tiktok-clone.appspot.com',
    iosBundleId: 'com.moztiq.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAECmv5DK5Z22nGYhmkE4mtB9Pt6FHyNs',
    appId: '1:77712420958:ios:d43934f9f58b402b4b84cf',
    messagingSenderId: '77712420958',
    projectId: 'moztiq-nc-tiktok-clone',
    storageBucket: 'moztiq-nc-tiktok-clone.appspot.com',
    iosBundleId: 'com.example.ncFlutterTiktok.RunnerTests',
  );
}
